export const ZONES = [
  'Centro',
  'Pitic',
  'Villa Satélite',
  'Perisur',
  'San Benito',
  'Bugambilias',
  'Prados del Sol',
  'Villa del Real',
  'Proyecto Río',
  'Villas del Lago',
  'Country Club',
  'Las Quintas',
  'Olivares',
  'Bachoco',
  'San Luis',
  'Horizontes',
  'Valle Verde',
]
